"""Models related to AI-generated metadata."""

from datetime import datetime
from typing import List, Optional

class LLMSuggestion:
    """Represents a suggestion generated by the LLM for titles and/or summary."""
    def __init__(
        self,
        id: int = None,
        job_id: Optional[int] = None,
        prompt_type: Optional[str] = None,
        model_used: Optional[str] = None,
        titles: Optional[List[str]] = None,
        suggested_summary: Optional[str] = None,
        created_at: Optional[datetime] = None,
    ):
        self.id = id
        self.job_id = job_id
        self.prompt_type = prompt_type
        self.model_used = model_used
        self.suggested_titles = titles or []
        self.suggested_summary = suggested_summary
        self.created_at = created_at or datetime.utcnow()

    def set_titles(self, titles: List[str]) -> None:
        """Set the list of suggested titles."""
        self.suggested_titles = titles

    def get_titles(self) -> List[str]:
        """Get the list of suggested titles."""
        return self.suggested_titles
