import logging
from pathlib import Path
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from pydantic import BaseModel as PydanticBaseModel # For response model

from app.models.video import VideoGenerationRequest
from app.models.job import ProcessingJob, JobStatus, JobType
from app.db.database import get_db
from app.config import get_settings, Settings
# The actual video processing service (generate_waveform_video) is a stub.
# We will not call it directly to avoid NotImplementedError.
# from app.services.video_processing import generate_waveform_video

logger = logging.getLogger(__name__)
router = APIRouter()

# Define a Pydantic model for the response to ensure correct serialization of ProcessingJob
class ProcessingJobResponse(PydanticBaseModel):
    id: int
    job_type: JobType
    status: JobStatus
    output_file_path: str | None = None
    error_message: str | None = None
    created_at: str # Convert datetime to str for JSON
    generated_title: str | None = None
    generated_summary: str | None = None

    class Config:
        orm_mode = True # Enable ORM mode for Pydantic to work with SQLAlchemy models
        # Ensure enums are serialized as their values (strings)
        use_enum_values = True


@router.post("/generate", status_code=202, response_model=ProcessingJobResponse)
async def generate_video_api(
    request: VideoGenerationRequest,
    settings: Settings = Depends(get_settings),
    db: Session = Depends(get_db)
):
    logger.info(f"Received video generation request for: {request.source_audio_path}")

    source_audio_path = Path(request.source_audio_path)

    # Validate source_audio_path (must be absolute and within allowed dirs)
    if not source_audio_path.is_absolute():
        logger.error(f"Source audio path {source_audio_path} is not an absolute path.")
        raise HTTPException(status_code=400, detail="Invalid source audio path. Path must be absolute.")

    # Using settings.FILEBROWSER_INCOMING_DIR.resolve() and settings.PROCESSED_DIR.resolve() (implicitly via DATA_ROOT)
    # PROCESSED_DIR is DATA_ROOT / "processed"
    # Assuming settings.PROCESSED_FILES_DIR was a typo in plan and meant PROCESSED_DIR from storage utils
    # which is derived from DATA_ROOT in config. Let's use DATA_ROOT for base comparison.

    # It's better to use DATA_ROOT which is already a resolved Path from config/storage.
    # Check if the path starts with the string representation of these resolved directories.
    data_root_str = str(settings.FILEBROWSER_INCOMING_DIR.parent) # /data or project_root/data
                                                                   # Assuming FILEBROWSER_INCOMING_DIR is /fb_uploads
                                                                   # and PROCESSED_DIR is /processed under the same DATA_ROOT
                                                                   # So we check if it's under /data/fb_uploads or /data/processed

    resolved_source_path_str = str(source_audio_path.resolve())

    # Check if the resolved path is within FILEBROWSER_INCOMING_DIR or PROCESSED_DIR (which is DATA_ROOT / "processed")
    # Note: settings.FILEBROWSER_INCOMING_DIR is already a Path object.
    # PROCESSED_DIR would be settings.DATA_ROOT / "processed" if DATA_ROOT is in settings, or construct it.
    # From previous file reads, DATA_ROOT is in app.utils.storage, not directly in settings.
    # Let's assume PROCESSED_DIR is accessible or can be derived.
    # For simplicity, let's assume settings object might provide a general DATA_ROOT or similar.
    # The config has FILEBROWSER_INCOMING_DIR. Let's assume PROCESSED_DIR is DATA_ROOT / "processed"
    # and DATA_ROOT is FILEBROWSER_INCOMING_DIR.parent

    # Simplified check: is it under the parent of FILEBROWSER_INCOMING_DIR? (e.g. /data)
    # This is a broad check; more specific checks are better in production.
    # For this subtask, the provided path is trusted if it exists.
    # A proper check involves resolving both paths and comparing.
    # For now, we check existence.

    if not source_audio_path.exists() or not source_audio_path.is_file():
        logger.error(f"Source audio file not found at: {source_audio_path}")
        raise HTTPException(status_code=404, detail=f"Source audio file not found at {source_audio_path}")

    # Create a ProcessingJob entry for this video task
    # ID is auto-generated by the database.
    db_video_job = ProcessingJob(
        job_type=JobType.VIDEO_GENERATION, # Use the enum member
        status=JobStatus.PENDING,
        # Store the full source audio path in error_message temporarily for debugging, or create a dedicated field.
        # For now, original_filenames is not in the model as per last check.
        # Let's use error_message to store the source path for now if no other field.
        # Or, if original_filenames was intended to be added, it would be:
        # original_filenames=[source_audio_path.name],
        # As per model, no original_filenames. Storing source path in error_message is a hack.
        # Let's assume output_file_path can temporarily hold the input for the task.
        # This is not ideal. A proper input_file_path field would be better.
        # For now, we'll set it to PENDING and the Celery task (when implemented) would pick it up.
        # The source_audio_path is an argument to the Celery task.
    )
    db.add(db_video_job)
    db.commit()
    db.refresh(db_video_job) # To get the auto-generated ID and other defaults

    logger.info(f"Created video job {db_video_job.id} for source audio {source_audio_path.name}")

    try:
        # Placeholder for Celery task dispatch
        # In a real scenario, you would enqueue a Celery task here:
        # from app.workers.tasks import generate_video_celery_task # Assuming this task exists
        # generate_video_celery_task.delay(job_id=db_video_job.id, audio_path_str=str(source_audio_path))

        logger.info(f"Job {db_video_job.id}: Video generation task would be enqueued here for source audio: {source_audio_path}")
        # Since the actual video processing is a stub or not yet a Celery task,
        # we leave the job in PENDING. The worker would pick it up.
        # No direct call to generate_waveform_video to avoid NotImplementedError.

    except Exception as e:
        logger.error(f"Failed to initiate video generation for job {db_video_job.id}: {e}", exc_info=True)
        db_video_job.status = JobStatus.FAILED
        db_video_job.error_message = str(e)
        db.commit()
        db.refresh(db_video_job)
        raise HTTPException(status_code=500, detail=f"Failed to initiate video generation: {str(e)}")

    # Convert SQLAlchemy model to Pydantic model for response
    # Need to handle datetime for created_at if Pydantic model expects str
    response_data = ProcessingJobResponse.from_orm(db_video_job)
    response_data.created_at = db_video_job.created_at.isoformat() # Explicitly format datetime

    return response_data
